light_salt/light_salt/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from . import view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view.main, name='main'),
    path('media/', include('video.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('mychurch/', include('mychurch.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

light_salt/mychurch/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView

from mychurch.views import MychurchIndex, Board, BoardView, BoardWrite, BoardEdit, DeleteFile, \
     Comments, ImageUpload, ImageDelete, ImageRecovery,MychurchAdmin, MyMembers, MyBoards, MyBoard
from mychurch import views

app_name = 'mychurch'

urlpatterns = [
    # ex: /mychurch/
    path('', MychurchIndex.as_view(), name='index'),
    path('admin/<int:church_no>/', MychurchAdmin.as_view(), name='myadmin'),
    path('admin/<int:church_no>/mymembers/', MyMembers.as_view(), name='mymembers'),
    path('admin/<int:church_no>/myboards/', MyBoards.as_view(), name='myboards'),
    path('admin/<int:church_no>/myboards/<int:board_no>/', MyBoard.as_view(), name='myboard'),
    path('board/', Board.as_view(), name='board_index'),
    path('board/<int:board_no>/', Board.as_view(), name='board_list'),
    path('board/<int:board_no>/view/<int:board_content_no>/', BoardView.as_view(), name='board_view'),
    path('board/<int:board_no>/view/<int:board_content_no>/comment/', Comments.as_view(), name='comment'),
    path('board/<int:board_no>/edit/<int:board_content_no>/', BoardEdit.as_view(), name='board_edit'),
    path('board/<int:board_no>/reply/<int:board_content_no>/', BoardWrite.as_view(), name='board_reply'),
    path('board/<int:board_no>/write/', BoardWrite.as_view(), name='board_write'),
    path('board/<int:board_no>/image/upload/', views.ImageUpload, name='image_upload'),
    path('board/<int:board_no>/image/delete/', views.ImageDelete, name='image_delete'),
    path('board/<int:board_no>/image/recovery/', views.ImageRecovery, name='image_recovery'),
    path('board/<int:board_no>/view/download/<path:filename>/', views.FileDownload, name='file_download'),
    path('board/<int:board_no>/delete/<int:board_content_no>/', views.DeleteContents, name='board_delete'),
    path('board/<int:board_no>/delete/<int:board_content_no>/<int:file_attach_no>/<path:filename>/', views.DeleteFile, name='file_delete')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

light_salt/video/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.media, name='media'),
]

light_salt/mychurch/forms.py
from django import forms
from .models import LSCH004M, LSCH005D

def min_length_2_validator(value):
    if len(value) < 2:
        raise forms.ValidationError('2글자 이상 입력해주세요')
	
class BoardForm(forms.Form):
    subject = forms.CharField(validators=[min_length_2_validator], widget=forms.TextInput(attrs={'size':'50'}))
    content = forms.CharField(validators=[min_length_2_validator], widget=forms.Textarea(attrs={'id':'lightsalt'}))
    password = forms.CharField(widget=forms.PasswordInput(), required = False)
    board_no = forms.CharField(widget=forms.HiddenInput())
    user_id = forms.CharField(widget=forms.HiddenInput())
    #file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)

    class Meta:
        model = LSCH004M

    def __init__(self, request, *args, **kwargs):
        self.file_attach_yn = kwargs.pop('file_attach_yn',None)
        if self.file_attach_yn == 'Y':
            self.fields['file_field'] = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)
        super(BoardForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, group_order=1, group_no=1, depth=0):
        content = LSCH004M(**self.cleaned_data)
        content.group_order = group_order
        content.group_no = group_no
        content.depth = depth
        #post = LSCH004M(**self.cleaned_data)
        if commit:
            content.save()
        return content

light_salt/mychurch/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.db import connection, transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import LSCH004M, LSCH003M, LSCH006D, LSCH005D
from  account.models import LightSaltUser, Believer

from django.views.generic import TemplateView, UpdateView
from django.shortcuts import get_object_or_404
from mychurch.pagingHelper import pagingHelper
from datetime import date, datetime
from django.core.files.storage import FileSystemStorage
from django.forms import forms
from django.conf import settings
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import loader
from html.parser import HTMLParser
from .forms import BoardForm


class MyHTMLParser(HTMLParser): 
    def __init__(self, *args, **kwargs):
        self.data_list = []
        HTMLParser.__init__(self, *args, **kwargs)

    def handle_starttag(self, tag, attrs):
        if tag == 'img':
            for (attr, value) in attrs:
                if attr =='src':
                    self.data_list.append(value)				

    def get_image_set(self):
        return self.data_list

class MyBoard(TemplateView) :
    def get(self,request, church_no, board_no):
        page = request.GET.get('page')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        if  int(board_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        board = get_object_or_404(LSCH003M, pk=board_no)

        return render(request, 'mychurch/admin/mychurch_board_modify.html',{'church_no':church_no, 'board_no':board_no, 'page':page, 'board':board} )

    def post(self,request, church_no, board_no):
        page = request.POST.get('page')
        board_title_name = request.POST.get('board_title_name')
        member_id = request.POST.get('member_id')
        page_count = request.POST.get('page_count')
        list_count = request.POST.get('list_count')
        board_type_code = request.POST.get('board_type_code')
        board_access_code = request.POST.get('board_access_code')
        file_attach_yn = request.POST.get('file_attach_yn')
        comment_use_yn = request.POST.get('comment_use_yn')
        passwd_use_yn = request.POST.get('passwd_use_yn')
        webedit_use_yn = request.POST.get('webedit_use_yn')
        image_height = request.POST.get('image_height')
        image_width = request.POST.get('image_width')
        image_br_count = request.POST.get('image_br_count')
        new_icon_terms = request.POST.get('new_icon_terms')
        hot_view_count = request.POST.get('hot_icon_view_count')

        LSCH003M.objects.filter(pk=board_no).update( member_id=member_id, board_title_name=board_title_name, list_count=list_count, page_count=page_count, \
            board_type_code=board_type_code, board_access_code=board_access_code,file_attach_yn=file_attach_yn,comment_use_yn=comment_use_yn,  \
            image_br_count=image_br_count, image_height=image_height, image_width=image_width, new_icon_terms=new_icon_terms , passwd_use_yn=passwd_use_yn, \
            webedit_use_yn=webedit_use_yn, hot_icon_view_count=hot_view_count, user_id=request.user.member_id)

        view = MyBoards() 
        if not request.GET._mutable:
            request.GET._mutable = True
        
        request.GET['page'] = page
        return view.get(request, church_no)
        #return redirect('mychurch:myboards', church_no=church_no, page=page)

class MyBoards(TemplateView) :

    def get(self,request, church_no):

        page = request.GET.get('page')
        mode = request.GET.get('mode')

        if page is None :
            page=1

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')
			
        if mode=="write" :
            return  render(request, 'mychurch/admin/mychurch_board_add.html',{'church_no':church_no, 'page':page} )
        else :
            boards =  LSCH003M.objects.raw('''SELECT a.board_no, a.board_title_name, a.board_type_code, a.board_access_code, a.file_attach_yn, a.comment_use_yn, a.passwd_use_yn FROM LSCH003M as a WHERE a.church_no = %s''', [church_no])
            paginator = Paginator(list(boards), 20) 

            try:
                page_list = paginator.page(page)
            except PageNotAnInteger:
                page_list = paginator.page(1)
            except EmptyPage:
                page_list = paginator.page(paginator.num_pages)
           
            return  render(request, 'mychurch/admin/mychurch_boards.html',{'church_no':church_no, 'boards':boards,   'page_list': page_list, 'page':page} )
    
    def post(self,request, church_no):
        page = request.POST.get('page')
        board_title_name = request.POST.get('board_title_name')
        member_id = request.POST.get('member_id')
        page_count = request.POST.get('page_count')
        list_count = request.POST.get('list_count')
        board_type_code = request.POST.get('board_type_code')
        board_access_code = request.POST.get('board_access_code')
        file_attach_yn = request.POST.get('file_attach_yn')
        comment_use_yn = request.POST.get('comment_use_yn')
        passwd_use_yn = request.POST.get('passwd_use_yn')
        webedit_use_yn = request.POST.get('webedit_use_yn')
        image_height = request.POST.get('image_height')
        image_width = request.POST.get('image_width')
        image_br_count = request.POST.get('image_br_count')
        new_icon_terms = request.POST.get('new_icon_terms')
        hot_view_count = request.POST.get('hot_view_count')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')
        
        result = LSCH003M.objects.create(church_no=church_no, member_id=member_id, board_title_name=board_title_name, list_count=list_count, page_count=page_count, \
            board_type_code=board_type_code, board_access_code=board_access_code,file_attach_yn=file_attach_yn,comment_use_yn=comment_use_yn,  \
            image_br_count=image_br_count, image_height=image_height, image_width=image_width, new_icon_terms=new_icon_terms , passwd_use_yn=passwd_use_yn, \
            webedit_use_yn=webedit_use_yn, hot_icon_view_count=hot_view_count, user_id=request.user.member_id)

        return redirect('mychurch:myboards', church_no=church_no)

class MychurchAdmin(LoginRequiredMixin, TemplateView):

    def get(self,request, church_no):

        if    int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        return  render(request, 'mychurch/admin/admin.html',{'church_no':church_no} )

class MyMembers(LoginRequiredMixin, TemplateView):
    #To-Do : code 정보에서 추출
    duty_cd = {'D001':'목사', 'D002':'장로', 'D003':'집사', 'D004':'일반신도'}

    #교인목록 조회
    def get(self,request, church_no):

        page = request.POST.get('page')
        searchStr = request.GET.get('searchStr')
        searchKey = request.GET.get('searchKey')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

       # members = Believer.objects.filter(church_no_id=church_no).select_related('LightSaltUser__id').values( 'nick_name','duty_code', 'consult_yn', 'board_create_yn')
        if searchKey == "nick":
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id AND a.nick_name LIKE CONCAT('%%',%s,'%%')""", [church_no, searchStr])
        elif searchKey == 'id' :
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id AND b.member_id LIKE CONCAT('%%',%s,'%%')""", [church_no, searchStr])
        elif searchKey == 'duty' :
            #TO-DO : join with code table for searching..
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id""", [church_no])
        else :
             members =  Believer.objects.raw('''SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active FROM LSMB003I as a , LSMB001M as b WHERE a.church_no_id = %s AND a.member_id_id=b.id''', [church_no])
        
        paginator = Paginator(list(members), 20) # Show count board list per page
        try:
            page_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            page_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            page_list = paginator.page(paginator.num_pages)
        
        return  render(request, 'mychurch/admin/mychurch_members.html',{'church_no':church_no, 'members':members,  'duty_cd':self.duty_cd, 'page_list': page_list, 'page':page} )

    def post(self,request, church_no):
         #
        memberId = request.POST.get('member_id')
        memberNo = request.POST.get('member_no')
        type = request.POST.get('type')
        item = request.POST.get('item')
        value = request.POST.get('val')

        if type == 'M':
            LightSaltUser.objects.filter(member_id=memberId).update(**{item: value})
        else:

light_salt/templates/light_salt/mychurch/index.html
{% extends 'base.html' %}

{% block content %}
<div class="columns">
	<div id="light-salt" v-cloak>
      <!-- Django을 이용한 목록 출력 -->
	  <p v-html="title1"></p>   
	  
	  <ul>
       {% for day in days %}
         <li><h4> Django Day {{ day }}</h4></li>
       {% endfor %}
      </ul>
	  
	  <!-- Vue을 이용한 목록 출력 -->
	  <p><b>[[title2]]([[Date()]])<b></p>  
	    <ul>
          <li v-for="(todo, index) in todos">
            <h4> [[index+1]] Day [[ todo.text]]</h4>
          </li>
        </ul>
		
	  <h1>카운터: [[ number ]]</h1>
      <button @click="increment">증가</button>
      <button @click="decrement">감소</button>
	</div>
</div>
	<script>
	new Vue({
	  delimiters: ['[[', ']]'],
	  el: '#light-salt',
	  data: {
		title1: '<b>Django list test</b>',
		title2: 'Vue list test',
		todos: [
		  { text: 'Vue.js 튜토리얼 작성하기' },
		  { text: 'Webpack2 알아보기' },
		  { text: '사이드 프로젝트 진행하기' }
		],
		number: 0
	  },
	  methods: {
		increment: function() {
		  this.number++;
		},
		decrement: function() {
		  this.number--;
		}
	  }
	})
	</script>
{% endblock content %}

light_salt/templates/light_salt/mychurch/main.html
<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>빛과소금 - 교회</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
		<!-- Bulma Version 0.7.1-->
		{% load static %}  
		<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>  
        <script src="{% static 'js/vue/vue.min.js' %}"></script>
		<link rel="stylesheet" href="{% static 'css/bulma.min.css' %}" />
		<script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
		<style>
		  html,body {
		    font-family: 'Malgun Gothic','Nanum Gothic','Nanum GothicB', 'Open Sans', serif;
		    background: #FFFFFF;
		  }
		  .columns {
			margin-top: 0;
		  }
		  section.column {
			padding: 1rem;
			font-size: 0.95rem;
		  }
		  .sidebar-header-single {
			color: #000;
			font-weight: 100;
			font-size: 0.95rem;
			border-left: 4px solid #ff0083;
			padding-left: 0.75rem;
		  }
          .menu-label {
		    padding: 0rem;
			font-size: 0.9rem;
		  }
		</style>
		
	</head>
	<body>
     <section class="hero is-info">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    하늘 교회
                </h1>
                <h2 class="subtitle">
                    평화가 함께하는 온라인 교회
                </h2>
            </div>
        </div>
    </section>
    
	<div class="columns is-3">				
	  <section class="column">
		<div class="tile is-ancestor">
			<div class="tile is-vertical is-10">
				<div class="tile">
					<div class="tile is-4 is-parent is-vertical">
					  <div class="column is-12">
						<div class="card">
						      <header class="card-header notification is-link">
						        <p class="card-header-title">
							   <font color="white">{{ boardTitle.0 }}</font>
                                                                       </p>
                                                                       <a href="{% url 'mychurch:board_list' board_no=boardNo.0 %}" class="card-header-icon" aria-label="more options">
						          <span class="icon">
							    <i class="fa fa-angle-down" aria-hidden="true"></i>
						          </span>
						    </a>
	                                                         </header>
						   <table cellspacing=3 class="table is-striped is-fullwidth is-hoverable">
							  <tbody>
							  {% if noticeList %}
							    {% for row in noticeList %}
							      <tr>
								    <td>{{ row.create_time|date:"Y-m-d" }}</td>
								    <td><a href="{% url 'mychurch:board_view' board_no=boardNo.0 board_content_no=row.board_content_no %}">{{ row.subject }}</a><td>
								  </tr>
								{% endfor %}
								 
							  {% else %}
								  <tr>
								    <td colspan=2 align="center">No Data<td>
								  </tr>
							  {% endif %}
							  
							  </tbody>
							</table>
						</div>
					  </div>	
	                  <div class="column is-12">
						<div class="card">
							<header class="card-header notification is-link">
                                <p class="card-header-title ">
                                    <font color="white">{{ boardTitle.1 }}</font>
                                </p>
                                <a href="{% url 'mychurch:board_list' board_no=boardNo.1 %}" class="card-header-icon" aria-label="more options">
								  <span class="icon">
									<i class="fa fa-angle-down" aria-hidden="true"></i>
								  </span>
								</a>
                             </header>
							 <div class="card-table">
                                <div class="content">
                                    <table class="table is-fullwidth is-striped is-hoverable">
                                        <tbody>
										{% if counselList %}
										  {% for row in counselList %}
                                            <tr>
                                                <td width="5%"><i class="fa fa-bell-o"></i></td>
                                                <td><a href="{% url 'mychurch:board_view' board_no=boardNo.1 board_content_no=row.board_content_no %}">{{ row.subject }}</td>    
                                            </tr>
										  {% endfor %}	
										{% else %}
											<tr>
											    <td colspan=2 align="center">No Data<td>
											</tr>
										 {% endif %}
                                                                                                                            
                                        </tbody>
                                    </table>
                                </div>
                            </div>
						</div>
					  </div> 
					</div>
					<div class="tile is-parent is-8">
						<article class="tile is-child notification">
							<figure class="image is-4by3">
								<img src="https://bulma.io/images/placeholders/640x480.png" >
							</figure>
						</article>
					</div>
				</div>
			  <div class="tile is-ancestor">
			  {% if imgList %}
				{% for row in imgList %}
				<div class="tile is-parent">
					<article class="tile is-child box">
                        <figure ><a href="{% url 'mychurch:board_view' board_no=boardNo.2 board_content_no=row.board_content_no %}">
                            <img src="{{ row.path }}" width="150" height="180" border=0>
                        </figure>
                        <p class="subtitle">{{ row.subject }}</p></a>
                        <div class="content is-8">{{ row.create_time|date:"Y-m-d h:i:s" }}</div>
                    </article>
				</div>
				{% endfor %}
			  {% else %}
				    <div class="tile is-parent">
					    <article class="tile is-child box">
						    <p class="subtitle">No Data</p>
						</article>
					</div>
			  {% endif %}
				
				
			  </div>
			</div>
			<div class="tile is-2 is-parent">
			
				<div class="card-wrapper">
					<div class="card">
					<header class="card-header-fix-center has-text-centered notification is-danger">
					  <p class="card-header-title-fix">
						About
					  </p>
					</header>
					<div class="card-content">
					  <div class="content">
						<div class="sidebar-header-single">홍길동(장로) </div><br>
					    <ul>
						<li>현재 접속자수 : 100명</li>
						<li>전체 교인수 : 356명</li>
						</ul>
						<a class="button is-dark">회원정보</a>&nbsp;<a class="button is-focused">관리자</a>
					  </div>
					</div>
					
				</div>
				<br>
			    <div class="card-wrapper">
				  	<div class="card">						
						{% load mychurch_tags %}
					    {% side_menu %}	
				
					</div>
		        </div>
			</div>
		</div>
      </section>
	
	
	</div>
	
		
	<footer class="footer">
			<div class="container">
				<div class="content has-text-centered">
					<div class="columns is-mobile is-centered">
						<div class="field is-grouped is-grouped-multiline">
							<div class="control">
								<div class="tags has-addons">
								  
								  <a class="tag is-link" href="#">
								    <span class="icon">
								      <i class="fas fa-home"></i>
								    </span>
								    빛과소금
								  </a>
								  <span class="tag is-light">연락처 : 02-xxxx-xxxx </span>
								</div>
							</div>
							<div class="control">
								<div class="tags has-addons">
									<span class="tag is-light">인천시 서구 봉화로 60-17 &nbsp;</span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
	</body>
</html>

light_salt/templates/light_salt/mychurch/menu.html
                        <header class="card-header-fix-center has-text-centered notification is-info">
						  <p class="card-header-title-fix">
							우리 교회
						  </p>
						</header>
						<div class="card-content">
						{% for menu in menu_list %}
						
						  <p class="menu-label">
						    <a href="{{ menu.menu_link_addr}}">{{menu.menu_name}}</a>
						  </p>
						  
						{% endfor %}
						</div>