light_salt/light_salt/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from . import view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view.main, name='main'),
    path('media/', include('video.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('mychurch/', include('mychurch.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

light_salt/mychurch/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView

from mychurch.views import MychurchIndex, Board, BoardView, BoardWrite, BoardEdit, DeleteFile, \
     Comments, ImageUpload, ImageDelete, ImageRecovery,MychurchAdmin, MyMembers, MyBoards, MyBoard
from mychurch import views

app_name = 'mychurch'

urlpatterns = [
    # ex: /mychurch/
    path('', MychurchIndex.as_view(), name='index'),
    path('admin/<int:church_no>/', MychurchAdmin.as_view(), name='myadmin'),
    path('admin/<int:church_no>/mymembers/', MyMembers.as_view(), name='mymembers'),
    path('admin/<int:church_no>/myboards/', MyBoards.as_view(), name='myboards'),
    path('admin/<int:church_no>/myboards/<int:board_no>/', MyBoard.as_view(), name='myboard'),
    path('board/', Board.as_view(), name='board_index'),
    path('board/<int:board_no>/', Board.as_view(), name='board_list'),
    path('board/<int:board_no>/view/<int:board_content_no>/', BoardView.as_view(), name='board_view'),
    path('board/<int:board_no>/view/<int:board_content_no>/comment/', Comments.as_view(), name='comment'),
    path('board/<int:board_no>/edit/<int:board_content_no>/', BoardEdit.as_view(), name='board_edit'),
    path('board/<int:board_no>/reply/<int:board_content_no>/', BoardWrite.as_view(), name='board_reply'),
    path('board/<int:board_no>/write/', BoardWrite.as_view(), name='board_write'),
    path('board/<int:board_no>/image/upload/', views.ImageUpload, name='image_upload'),
    path('board/<int:board_no>/image/delete/', views.ImageDelete, name='image_delete'),
    path('board/<int:board_no>/image/recovery/', views.ImageRecovery, name='image_recovery'),
    path('board/<int:board_no>/view/download/<path:filename>/', views.FileDownload, name='file_download'),
    path('board/<int:board_no>/delete/<int:board_content_no>/', views.DeleteContents, name='board_delete'),
    path('board/<int:board_no>/delete/<int:board_content_no>/<int:file_attach_no>/<path:filename>/', views.DeleteFile, name='file_delete')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

light_salt/video/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.media, name='media'),
]

light_salt/mychurch/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/<id>/Ymd/<filename>
    return '{0}/%Y%m%d/{1}'.format(instance.user.id, filename)
	
#교회Layout 
class LSCH001M(models.Model):
    layout_no = models.AutoField(primary_key=True)
    church_no = models.IntegerField(null=False, default=0)
    template_no = models.IntegerField(null=False, default=0)
    layout_pos = models.IntegerField(null=False, default=1)
    content = models.TextField(null=False)
    content_type_code = models.CharField(max_length=6, null=False)
    object_id = models.CharField(max_length=50, null=True)
    disp_count = models.IntegerField(null=False, default=5 )   
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)	
   
    class Meta:
        db_table = "LSCH001M"

    def __str__(self):
       return self.name

#교회Layout template 종류
class LSCH002M(models.Model):
    template_no = models.AutoField(primary_key=True)
    template_object_id = models.CharField(max_length=50, null=True)
    template_partition_count = models.IntegerField(null=False, default=1)
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)	
   
    class Meta:
        db_table = "LSCH002M"

    def __str__(self):
        return self.name

#게시판관리
class LSCH003M(models.Model):
    board_no = models.AutoField(primary_key=True)
    church_no = models.IntegerField(null=False, default=0)
    member_id = models.CharField(max_length=20, null=False)	
    board_title_name = models.CharField(max_length=100, null=True)	
    list_count = models.IntegerField(null=False, default=10)
    page_count = models.IntegerField(null=False, default=10)
    board_type_code = models.CharField(max_length=6, null=False)
    board_access_code = models.CharField(max_length=6, null=False)
    file_attach_yn = models.CharField(max_length=10, null=False, default="Y")
    comment_use_yn = models.CharField(max_length=10, null=False, default="Y")
    webedit_use_yn = models.CharField(max_length=10, null=False, default="Y")
    passwd_use_yn = models.CharField(max_length=10, null=False, default="N")
    new_icon_terms = models.IntegerField(null=False, default=2)
    hot_icon_view_count = models.IntegerField(null=False, default=1000)
    image_width = models.IntegerField(null=False, default=180)
    image_height = models.IntegerField(null=False, default=200)
    image_br_count = models.IntegerField(null=False, default=4)
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = "LSCH003M"

    def __str__(self):
       return self.name

    def get_church_alllist(no): 
        listInfo = LSCH003M.objects.filter(
            church_no=no
        )
        return listInfo

#게시글	정보
class LSCH004M(models.Model):
    board_content_no = models.AutoField(primary_key=True)
    board_no = models.IntegerField(null=False, default=0)
    subject = models.CharField(max_length=100, null=False)	
    content = models.TextField(null=False)
    group_no = models.IntegerField(null=False, default=1)
    group_order = models.IntegerField(null=False, default=1)
    depth = models.IntegerField(null=False, default=0)
    hit_count = models.IntegerField(null=False, default=0)
    password = models.CharField(max_length=50, null=True)	
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = "LSCH004M"
		
    def __str__(self):
        return self.name
   
    def get_board_list5(no):
        listInfo=LSCH004M.objects.filter(
            board_no=no
        ).order_by('-group_no', 'group_order')[:5]
        return listInfo

    #def get_absolute_url(self, **kwargs): # redirect시 활용
    #    page=1
    #    if kwargs is not None:
    #        page = kwargs['page']		
    #    url = (("%s?page=%s") % (reverse('mychurch:board_list', args=[self.board_no]), page))
    #    return url

#댓글 정보
class LSCH005D(models.Model):
    board_content_no = models.IntegerField(null=False, default=0)
    comment_no = models.AutoField(primary_key=True)
    group_no = models.IntegerField(null=False, default=1)
    group_order = models.IntegerField(null=False, default=1)
    depth = models.IntegerField(null=False, default=0)
    comment = models.CharField(max_length=2000, null=False)	
    secret_comment_yn = models.CharField(max_length=10, null=False, default="N")
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = "LSCH005D"
        unique_together = (('board_content_no', 'comment_no'),)

    def __str__(self):
       return self.name

    def get_comment_all(no): 
        commentList = LSCH005D.objects.filter(
            board_content_no=no
        ).order_by('-group_no', 'group_order')
        return commentList

#첨부파일 정보
import os
class LSCH006D(models.Model):
    board_content_no = models.IntegerField(null=False, default=0)
    file_attach_no = models.IntegerField(null=False, default=0, primary_key=True)
    file_name = models.CharField(max_length=200, null=False)	
    file_size = models.IntegerField(null=False, default=0)
    file_type_code = models.CharField(max_length=6, null=False)
    download_count = models.IntegerField(null=False, default=0)
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = "LSCH006D"
        unique_together = (('board_content_no', 'file_attach_no'),)

    def get_board_list(no):
        listInfo=LSCH006D.objects.filter(
            board_content_no=no
        ).exclude(
            file_type_code = "IMG"
        )
        return listInfo

    @property
    def filename(self):
        return os.path.basename(self.file_name)

    def __str__(self):
       return self.name

#메뉴 정보
class LSCH007M(models.Model):
    menu_no = models.AutoField(primary_key=True)
    church_no = models.IntegerField(null=False, default=0)
    board_no = models.IntegerField(null=False, default=0) #메뉴가 게시판 종류 일때만...
    menu_name = models.CharField(max_length=100, null=False)	
    menu_link_addr = models.CharField(max_length=100, null=False)
    menu_order = models.IntegerField(null=False, default=0)
    create_time = models.DateTimeField(auto_now_add=True, null=False)
    modify_time = models.DateTimeField(auto_now=True, null=False)
    user_id = models.CharField(max_length=20, null=False)

    class Meta:
        db_table = "LSCH007M"

    def __str__(self):
       return self.name

light_salt/mychurch/forms.py
from django import forms
from .models import LSCH004M, LSCH005D

def min_length_2_validator(value):
    if len(value) < 2:
        raise forms.ValidationError('2글자 이상 입력해주세요')
	
class BoardForm(forms.Form):
    subject = forms.CharField(validators=[min_length_2_validator], widget=forms.TextInput(attrs={'size':'50'}))
    content = forms.CharField(validators=[min_length_2_validator], widget=forms.Textarea(attrs={'id':'lightsalt'}))
    password = forms.CharField(widget=forms.PasswordInput(), required = False)
    board_no = forms.CharField(widget=forms.HiddenInput())
    user_id = forms.CharField(widget=forms.HiddenInput())
    #file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)

    class Meta:
        model = LSCH004M

    def __init__(self, request, *args, **kwargs):
        self.file_attach_yn = kwargs.pop('file_attach_yn',None)
        if self.file_attach_yn == 'Y':
            self.fields['file_field'] = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)
        super(BoardForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, group_order=1, group_no=1, depth=0):
        content = LSCH004M(**self.cleaned_data)
        content.group_order = group_order
        content.group_no = group_no
        content.depth = depth
        #post = LSCH004M(**self.cleaned_data)
        if commit:
            content.save()
        return content

light_salt/templates/light_salt/mychurch/board/board_edit.html
{% extends 'mychurch/board/base.html' %}

{% block content %}
{% load mychurch_filter %}	

		<div class="tile is-8 is-vertical">	
		<form action="" method="post" name="fm" enctype="multipart/form-data">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<input type="hidden" name="board_no" value="{{ board_no }}">
			<input type="hidden" name="user_id" value="{{ board_contents.user_id }}">
			<input type="hidden" name="file_attach_yn" value="{{ board_conf.file_attach_yn }}">
			<input type="hidden" name="page" value="{{ page }}">
			<div class="card">
				<div class="card-content">
					<div class="field">
						<label class="label">제목</label>
						<div class="control">
							<input type="text" value="{{ board_contents.subject }}" name="subject" required id="id_subject" />
						</div>
					</div>
					<div class="field">
						<label class="label">내용</label>
						<div class="control">
						    <textarea name="content" id="lightsalt" required>{{ board_contents.content|safe }}
                            </textarea>
						</div>
					</div>
					{% if board_conf.file_attach_yn == 'Y' %}				
					<div class="field">
						<label class="label">첨부파일</label>
						<div class="control">
						{% for file in file_list %}
						    {{file.file_name|getFilename|unsetQuote}}<a href="{% url 'mychurch:file_delete' board_no=board_no board_content_no=board_contents.board_content_no file_attach_no=file.file_attach_no filename=file.file_name|setQuote %}">&nbsp;[삭제]</a><br>
						{% endfor %}
						</div>
						<label for="id_file_field">파일첨부:</label>
					    <input type="file" name="file_field" multiple id="id_file_field" />
					</div>
				   {% endif %}
				   
				   {% if board_contents.password %}
					<div class="field">
						<label class="label">비밀번호</label>
						<input type="password" name="password" id="id_password" value="" />
					</div>
					{% endif %}
				</div>
				</form>
				<footer class="card-footer">
					<p class="card-footer-item">
						<span>
							<a href="javascript:_submit()" class="button is-link is-active">저장</a>
						</span>
					</p>
					<p class="card-footer-item">
						<span>
							<a href="{% url 'mychurch:board_list' board_no=board_no %}?page={{page}}" class="button is-link is-active">목록</a>
						</span>
					</p>
				</footer>
			</div>			
		</div>
	<script>
  var justDeletedImg = "";
  var justDeletedFile = "";
  var default_init = "";
  var prev_changed_block_id = "";
  var csrf_token = '{{ csrf_token }}';
  var imageUploadUrl="{% url 'mychurch:image_upload' board_no=board_no %}";
  var deleteImageUrl="{% url 'mychurch:image_delete' board_no=board_no %}"
  var recoveryImageUrl="{% url 'mychurch:image_recovery' board_no=board_no %}"
  
    function _submit()
    {
	    f = document.fm
		if( f.subject.value == "") {
		    alert("제목을 입력하세요");
			return;
		}
		else if( f.content.value == "") {
		    alert("내용을 입력하세요");
			return;
		}
	    f.action="{% url 'mychurch:board_edit' board_no=board_no board_content_no=board_contents.board_content_no %}";
		f.submit();
	}

</script>		
<script src="/static/js/application/board_editor.js"></script>			
  {% endblock content %}    

light_salt/templates/light_salt/mychurch/board/board_list.html
{% extends 'mychurch/board/base.html' %}

{% block content %}
	<script>
       function _search()
	   {
	       var f = document.fm;
		   if( f.searchStr.value=="" ) {
		       alert("검색할 내용을 입력하세요");
			   f.searchStr.focus();
			   return;
		   }
		   f.action="{% url 'mychurch:board_list' board_no=board_conf.board_no %}";
		   f.submit();
	   }
    </script>	
		<div class="tile is-8 is-vertical">	
		    <br>
			<div class="control">
			     <h1 class="subtitle">{{ board_conf.board_title_name }}</h1>
			</div>
			<br>
			{% if board_conf.board_type_code == 'IMG' %}
			    {% include 'mychurch/board/gallery_list.html' %}
			{% else %}
			    {% include 'mychurch/board/default_list.html' %}
			{% endif %}
			<table class="table" align="center">
			    <form action="" method="post" name="fm" >
				<input type="hidden" name="page" value="{{page}}">
				{% csrf_token %}
			    <tr align="center">
				    <td align="center"><select name="searchKey">
					        <option value="1" >제목</option>
							<option value="2" >내용</option>
							<option value="3" >제목+내용</option>
					    </select>
				       <input type="text" name="searchStr" value="{{ searchStr }}">
					  <a class="button is-link is-rounded" href="javascript:_search()">검색</a></td>
				</tr>
				</form>
			</table>
<!--
			<div align="center">
			<span>
			  <nav>
				<ul class="pagination">
				  {% if page_list.has_previous %}
					<li>
					  <a href="?page={{ page_list.previous_page_number }}">
						<span>Prev</span>
					  </a>
					</li>
				  {% else %}
					<li class="disabled">
					  <a href="#">
						<span>Previous</span>
					  </a>
					</li>
				  {% endif %}

				  {% for page in page_list.paginator.page_range %}
					<li {% if page == page_list.number %}class="active"{% endif %}>
					  <a href="?page={{ page }}">{{ page }}</a>
					</li>
				  {% endfor %}

				  {% if page_list.has_next %}
					<li>
					  <a href="?page={{ page_list.next_page_number }}">
						<span>Next</span>
					  </a>
					</li>
				  {% else %}
					<li {% if not page_list.has_next %}class="disabled"{% endif %}>
					  <a href="#">
						<span>Next</span>
					  </a>
					</li>
				  {% endif %}
				</ul>
			  </nav>
			</span>
			</div>
	-->
  			  <ul class="pagination">
				{% if page_list.has_previous %}
				  <li><a href="?page={{ page_list.previous_page_number }}">&laquo;</a></li>
				{% else %}
				  <li class="disabled"><span>&laquo;</span></li>
				{% endif %}
				{% for i in page_list.paginator.page_range %}
				  {% if page_list.number == i %}
					<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
				  {% else %}
					<li><a href="?page={{ i }}">{{ i }}</a></li>
				  {% endif %}
				{% endfor %}
				{% if page_list.has_next %}
				  <li><a href="?page={{ page_list.next_page_number }}">&raquo;</a></li>
				{% else %}
				  <li class="disabled"><span>&raquo;</span></li>
				{% endif %}
			  </ul>
	
<!--	
            <div class="pagination">
				<span class="step-links">
					{% if page_list.has_previous %}
						<a href="?page={{ page_list.previous_page_number }}">previous</a>
					{% endif %}

					<span class="current">
						Page {{ page_list.number }} of {{ page_list.paginator.num_pages }}.
					</span>

					{% if page_list.has_next %}
						<a href="?page={{ page_list.next_page_number }}">next</a>
					{% endif %}
				</span>
			</div>	
-->
        {% if board_conf.board_access_code == 'RDWR' %}
            <div class="level-right bd-structure-item">
			    <a class="button is-info is-hovered" href="{% url 'mychurch:board_write' board_no=board_conf.board_no %}">글쓰기</a>
            </div>	
        {% endif %}			
		</div>
	
  {% endblock content %}    

light_salt/templates/light_salt/mychurch/board/board_password.html
	
{% extends 'mychurch/board/base.html' %}

{% block content %}	
    
		<div class="tile is-8 is-vertical">	
			<div class="card">
				<div class="card-content">
				    <br><br>
				<form action="{% url 'mychurch:board_view' board_no=board_no board_content_no=board_content_no %}" method="get" name="frm">
				    {% csrf_token %}
					<input type="hidden" name="board_no" value="{{ board_no }}">
					<input type="hidden" name="board_content_no" value="{{ board_content_no }}">
					<input type="hidden" name="page" value="{{ page }}">
				    <b><small>{{ error_message }}</small></b><br>
					<div class="fieldWrapper">
						<label for="id_password">비밀번호:</label>
						<input type="password" value="" name="password_in" id="id_password_in" />
						&nbsp;&nbsp;<a href="javascript:_submit()" class="button is-link is-active">확인</a>
					</div>
				</form>
                </div>				
			</div>				
		</div>
<script>
  
  function _submit()
  {
    f = document.frm
	if( f.password_in.value == "") {
	    alert("비밀번호를 입력하세요");
		return;
	}

	f.submit();
  }

</script>		

{% endblock content %}    

light_salt/templates/light_salt/mychurch/board/board_view.html
{% extends 'mychurch/board/base.html' %}

{% block content %}
{% load mychurch_filter %}	
<style>
.comment {
    margin: 20px 0px 20px 20px;
}
</style>

		<div class="tile is-8 is-vertical">	
			<div class="card">
				<div class="card-content">
					<p class="title">
						{{ board_content.subject}}
					</p>
					<div class="field">
						<label class="label">제목</label>
						<div class="control">
							{{board_content.subject}}
						</div>
					</div>
					<div class="field">
						<label class="label">작성자</label>
						<div class="control">
							{{board_content.user_id}}
						</div>
					</div>
					<div class="field">
						<label class="label">조회수</label>
						<div class="control">
							{{board_content.hit_count}}
						</div>
					</div>
					<div class="field">
						<label class="label">작성일시</label>
						<div class="control">
							{{board_content.create_time|date:"Y-m-d h:i:s"}}
						</div>
					</div>
					<div class="field">
						<label class="label">내용</label>
						<div class="control">
							{{board_content.content|safe}}
						</div>
					</div>
					{% if board_conf.file_attach_yn == 'Y' %}				
					<div class="field">
					{% if file_list %}
						<label class="label">첨부파일</label>
						<div class="control">
						{% for file in file_list %}
						    <a href="{% url 'mychurch:file_download' board_no=board_no filename=file.file_name|unsetQuote %}">{{file.file_name|getFilename|unsetQuote}}</a><br>
						{% endfor %}
						</div>
					{% endif %}
					</div>
				   {% endif %}
				</div>

				<footer class="card-footer">
				{% if request.user.member_id == board_content.user_id and board_conf.board_access_code == 'RDWR' %}
					<p class="card-footer-item">
						<span>
							<a href="{% url 'mychurch:board_edit' board_content_no=board_content.board_content_no board_no=board_no %}?page={{page}}" class="button is-link is-active">수정</a>
						</span>
					</p>
					<p class="card-footer-item">
						<span>
							<a href="{% url 'mychurch:board_delete' board_content_no=board_content.board_content_no board_no=board_no %}?group_no={{board_content.group_no}}&group_order={{board_content.group_order}}&page={{page}}" class="button is-link is-danger">삭제</a>
						</span>
					</p>
				{%endif%}
				{% if board_conf.board_access_code == 'RDWR' %}
				    <p class="card-footer-item">
						<span>
							<a href="{% url 'mychurch:board_reply' board_content_no=board_content.board_content_no board_no=board_no %}?page={{page}}" class="button is-link is-active">답글</a>
						</span>
					</p>
				{%endif%}
					<p class="card-footer-item">
						<span>
							<a href="{% url 'mychurch:board_list' board_no=board_no %}?page={{page}}" class="button is-link is-active">목록</a>
						</span>
					</p>
				</footer>
			</div>		
            <div>
			    {% include 'mychurch/board/comment_form.html' %}
				{% if board_conf.comment_use_yn == 'Y' %}
			    <div id="comment_list">
			        {% include 'mychurch/board/comments.html' %}
				</div>
				{% endif %}	
			</div>
		</div>
			
  {% endblock content %}    

light_salt/templates/light_salt/mychurch/board/board_write.html
	
{% extends 'mychurch/board/base.html' %}

{% block content %}	

		<div class="tile is-8 is-vertical">	
			<div class="card">
				<div class="card-content">
				<form action="" method="post" name="frm" enctype="multipart/form-data">
				    {% csrf_token %}
					{{ form.non_field_errors }}
					<input type="hidden" name="board_no" value="{{ board_no }}">
					<input type="hidden" name="user_id" value="{{ user_id }}">
					<input type="hidden" name="file_attach_yn" value="{{ file_attach_yn }}">
					<input type="hidden" name="board_content_no" value="{{ board_content_no }}">
					<input type="hidden" name="content" value="">
					<input type="hidden" name="page" value="{{page}}">
					<div class="fieldWrapper">
						{{ form.subject.errors }}
						<label for="id_subject">제목:</label>
						{{ form.subject }}
					</div>
					<br>
					{{ form.content.errors }}
					<div class="fieldWrapper">
						{{ form.content.errors }}
						<textarea name="content" id="lightsalt" required></textarea>
					</div>
					<br>
	            {% if file_attach_yn == 'Y' %}				
					<div class="fieldWrapper">					
						<label for="id_file_field">파일첨부:</label>
						<input type="file" name="file_field" multiple id="id_file_field" />
					</div> 
					<br>
				{% endif %}	
					<div class="fieldWrapper">
						{{ form.password.errors }}
						<label for="id_password">비밀번호:</label>
						{{ form.password }}
					</div>
					<p><a href="javascript:_submit()" class="button is-link is-active">저장</a></p>
				</form>
                </div>				
			</div>				
		</div>
<script>
  var justDeletedImg = "";
  var justDeletedFile = "";
  var default_init = "";
  var prev_changed_block_id = "";
  var csrf_token = '{{ csrf_token }}';
  var imageUploadUrl="{% url 'mychurch:image_upload' board_no=board_no %}";
  var deleteImageUrl="{% url 'mychurch:image_delete' board_no=board_no %}"
  var recoveryImageUrl="{% url 'mychurch:image_recovery' board_no=board_no %}"
  
  function _submit()
  {
    f = document.frm
	if( f.subject.value == "") {
	    alert("제목을 입력하세요");
		return;
	}

{% if board_contents.password %}
    else if( f.password.value == "") {
	    alert("비밀번호를 입력하세요");
		return;
	}
{% endif %}	
    //alert(tinyMCE.get('lightsalt').getContent());
	
	f.submit();
  }

</script>		
<script src="/static/js/application/board_editor.js"></script>		

{% endblock content %}    

light_salt/templates/light_salt/mychurch/board/default_list.html
           <table class="table">
		   {% load staticfiles %} 
           {% load mychurch_filter %}	
			    <tr><th align="center">No.</th><th align="center">작성자</th>
				    <th align="center">제목</th><th align="center">작성일</th>
				</tr>
                {% for item in page_list %}
				  <tr>
				    <td>{{ item.board_content_no }}</td>
					<td>{{ item.user_id }}</td>
				    <td>{% if item.depth %}
					      {% for x in item.depth|times %}
						    &nbsp;&nbsp;
						  {%endfor%}
						  <img src="{% static 'img/icon_reply_head.gif' %}">
						{% endif %}
						<a href="{% url 'mychurch:board_view' board_no=board_conf.board_no board_content_no=item.board_content_no %}?page={{page}}">{{ item.subject }}</a>
					</td>
					<td>{{ item.create_time|date:"Y-m-d" }}</td>
				  </tr>
			    {% endfor %}
			</table> 

light_salt/templates/light_salt/mychurch/board/gallery_list.html
           <table class="table" width="800" cellpadding=0 cellspacing=0>
	{% load staticfiles %} 
           {% load mychurch_filter %}	
                <tr>
                {% for idx, item in page_list|enumerates %}
				  
				    <td align="left" height="160px"><table border=1 cellpadding=0 cellspacing=0>
					    <tr valign="bottom"><td align="center" height="130px" valign="top">
					    <a href="{% url 'mychurch:board_view' board_no=board_conf.board_no board_content_no=item.board_content_no %}?page={{page}}">
                                                      {% if item.content %}					
					    <img src="/mychurch{{item.content}}" width="180px" height="200px" border=0>
					{% else %}
					     <img src="{% static 'img/no_image.jpg' %}" width="180px" height="200px" border=0>  
					{% endif %}
						</td></tr>
						<tr align="center" valign="bottom"><td valign="bottom">
					          {% if item.depth %}
						  <img src="{% static 'img/icon_reply_head.gif' %}">
						{% endif %}
					          {{ item.subject }}</a><br>			
						{{ item.create_time|date:"Y-m-d"  }} | {{ item.hit_count }}
						<br>
						{{ item.user_id }}
						</td></tr>
						</table>
					</td>
				  {% if idx > 0 and idx|remainder:3 == 0 %}
                    </tr>
                    <tr>
				  {% endif %}	
			    {% endfor %}
				</tr>
			</table> 