light_salt/light_salt/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.urls import path
from . import view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', view.main, name='main'),
    path('media/', include('video.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('mychurch/', include('mychurch.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

light_salt/mychurch/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url
from django.conf import settings
from django.views.generic import TemplateView

from mychurch.views import MychurchIndex, Board, BoardView, BoardWrite, BoardEdit, DeleteFile, \
     Comments, ImageUpload, ImageDelete, ImageRecovery,MychurchAdmin, MyMembers, MyBoards, MyBoard
from mychurch import views

app_name = 'mychurch'

urlpatterns = [
    # ex: /mychurch/
    path('', MychurchIndex.as_view(), name='index'),
    path('admin/<int:church_no>/', MychurchAdmin.as_view(), name='myadmin'),
    path('admin/<int:church_no>/mymembers/', MyMembers.as_view(), name='mymembers'),
    path('admin/<int:church_no>/myboards/', MyBoards.as_view(), name='myboards'),
    path('admin/<int:church_no>/myboards/<int:board_no>/', MyBoard.as_view(), name='myboard'),
    path('board/', Board.as_view(), name='board_index'),
    path('board/<int:board_no>/', Board.as_view(), name='board_list'),
    path('board/<int:board_no>/view/<int:board_content_no>/', BoardView.as_view(), name='board_view'),
    path('board/<int:board_no>/view/<int:board_content_no>/comment/', Comments.as_view(), name='comment'),
    path('board/<int:board_no>/edit/<int:board_content_no>/', BoardEdit.as_view(), name='board_edit'),
    path('board/<int:board_no>/reply/<int:board_content_no>/', BoardWrite.as_view(), name='board_reply'),
    path('board/<int:board_no>/write/', BoardWrite.as_view(), name='board_write'),
    path('board/<int:board_no>/image/upload/', views.ImageUpload, name='image_upload'),
    path('board/<int:board_no>/image/delete/', views.ImageDelete, name='image_delete'),
    path('board/<int:board_no>/image/recovery/', views.ImageRecovery, name='image_recovery'),
    path('board/<int:board_no>/view/download/<path:filename>/', views.FileDownload, name='file_download'),
    path('board/<int:board_no>/delete/<int:board_content_no>/', views.DeleteContents, name='board_delete'),
    path('board/<int:board_no>/delete/<int:board_content_no>/<int:file_attach_no>/<path:filename>/', views.DeleteFile, name='file_delete')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

light_salt/video/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.media, name='media'),
]

light_salt/mychurch/forms.py
from django import forms
from .models import LSCH004M, LSCH005D

def min_length_2_validator(value):
    if len(value) < 2:
        raise forms.ValidationError('2글자 이상 입력해주세요')
	
class BoardForm(forms.Form):
    subject = forms.CharField(validators=[min_length_2_validator], widget=forms.TextInput(attrs={'size':'50'}))
    content = forms.CharField(validators=[min_length_2_validator], widget=forms.Textarea(attrs={'id':'lightsalt'}))
    password = forms.CharField(widget=forms.PasswordInput(), required = False)
    board_no = forms.CharField(widget=forms.HiddenInput())
    user_id = forms.CharField(widget=forms.HiddenInput())
    #file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)

    class Meta:
        model = LSCH004M

    def __init__(self, request, *args, **kwargs):
        self.file_attach_yn = kwargs.pop('file_attach_yn',None)
        if self.file_attach_yn == 'Y':
            self.fields['file_field'] = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}), required = False)
        super(BoardForm, self).__init__(*args, **kwargs)

    def save(self, commit=True, group_order=1, group_no=1, depth=0):
        content = LSCH004M(**self.cleaned_data)
        content.group_order = group_order
        content.group_no = group_no
        content.depth = depth
        #post = LSCH004M(**self.cleaned_data)
        if commit:
            content.save()
        return content

light_salt/mychurch/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.db import connection, transaction
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import LSCH004M, LSCH003M, LSCH006D, LSCH005D
from  account.models import LightSaltUser, Believer

from django.views.generic import TemplateView, UpdateView
from django.shortcuts import get_object_or_404
from mychurch.pagingHelper import pagingHelper
from datetime import date, datetime
from django.core.files.storage import FileSystemStorage
from django.forms import forms
from django.conf import settings
from django.db.models import F
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template import loader
from html.parser import HTMLParser
from .forms import BoardForm


class MyHTMLParser(HTMLParser): 
    def __init__(self, *args, **kwargs):
        self.data_list = []
        HTMLParser.__init__(self, *args, **kwargs)

    def handle_starttag(self, tag, attrs):
        if tag == 'img':
            for (attr, value) in attrs:
                if attr =='src':
                    self.data_list.append(value)				

    def get_image_set(self):
        return self.data_list

class MyBoard(TemplateView) :
    def get(self,request, church_no, board_no):
        page = request.GET.get('page')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        if  int(board_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        board = get_object_or_404(LSCH003M, pk=board_no)

        return render(request, 'mychurch/admin/mychurch_board_modify.html',{'church_no':church_no, 'board_no':board_no, 'page':page, 'board':board} )

    def post(self,request, church_no, board_no):
        page = request.POST.get('page')
        board_title_name = request.POST.get('board_title_name')
        member_id = request.POST.get('member_id')
        page_count = request.POST.get('page_count')
        list_count = request.POST.get('list_count')
        board_type_code = request.POST.get('board_type_code')
        board_access_code = request.POST.get('board_access_code')
        file_attach_yn = request.POST.get('file_attach_yn')
        comment_use_yn = request.POST.get('comment_use_yn')
        passwd_use_yn = request.POST.get('passwd_use_yn')
        webedit_use_yn = request.POST.get('webedit_use_yn')
        image_height = request.POST.get('image_height')
        image_width = request.POST.get('image_width')
        image_br_count = request.POST.get('image_br_count')
        new_icon_terms = request.POST.get('new_icon_terms')
        hot_view_count = request.POST.get('hot_icon_view_count')

        LSCH003M.objects.filter(pk=board_no).update( member_id=member_id, board_title_name=board_title_name, list_count=list_count, page_count=page_count, \
            board_type_code=board_type_code, board_access_code=board_access_code,file_attach_yn=file_attach_yn,comment_use_yn=comment_use_yn,  \
            image_br_count=image_br_count, image_height=image_height, image_width=image_width, new_icon_terms=new_icon_terms , passwd_use_yn=passwd_use_yn, \
            webedit_use_yn=webedit_use_yn, hot_icon_view_count=hot_view_count, user_id=request.user.member_id)

        view = MyBoards() 
        if not request.GET._mutable:
            request.GET._mutable = True
        
        request.GET['page'] = page
        return view.get(request, church_no)
        #return redirect('mychurch:myboards', church_no=church_no, page=page)

class MyBoards(TemplateView) :

    def get(self,request, church_no):

        page = request.GET.get('page')
        mode = request.GET.get('mode')

        if page is None :
            page=1

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')
			
        if mode=="write" :
            return  render(request, 'mychurch/admin/mychurch_board_add.html',{'church_no':church_no, 'page':page} )
        else :
            boards =  LSCH003M.objects.raw('''SELECT a.board_no, a.board_title_name, a.board_type_code, a.board_access_code, a.file_attach_yn, a.comment_use_yn, a.passwd_use_yn FROM LSCH003M as a WHERE a.church_no = %s''', [church_no])
            paginator = Paginator(list(boards), 20) 

            try:
                page_list = paginator.page(page)
            except PageNotAnInteger:
                page_list = paginator.page(1)
            except EmptyPage:
                page_list = paginator.page(paginator.num_pages)
           
            return  render(request, 'mychurch/admin/mychurch_boards.html',{'church_no':church_no, 'boards':boards,   'page_list': page_list, 'page':page} )
    
    def post(self,request, church_no):
        page = request.POST.get('page')
        board_title_name = request.POST.get('board_title_name')
        member_id = request.POST.get('member_id')
        page_count = request.POST.get('page_count')
        list_count = request.POST.get('list_count')
        board_type_code = request.POST.get('board_type_code')
        board_access_code = request.POST.get('board_access_code')
        file_attach_yn = request.POST.get('file_attach_yn')
        comment_use_yn = request.POST.get('comment_use_yn')
        passwd_use_yn = request.POST.get('passwd_use_yn')
        webedit_use_yn = request.POST.get('webedit_use_yn')
        image_height = request.POST.get('image_height')
        image_width = request.POST.get('image_width')
        image_br_count = request.POST.get('image_br_count')
        new_icon_terms = request.POST.get('new_icon_terms')
        hot_view_count = request.POST.get('hot_view_count')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')
        
        result = LSCH003M.objects.create(church_no=church_no, member_id=member_id, board_title_name=board_title_name, list_count=list_count, page_count=page_count, \
            board_type_code=board_type_code, board_access_code=board_access_code,file_attach_yn=file_attach_yn,comment_use_yn=comment_use_yn,  \
            image_br_count=image_br_count, image_height=image_height, image_width=image_width, new_icon_terms=new_icon_terms , passwd_use_yn=passwd_use_yn, \
            webedit_use_yn=webedit_use_yn, hot_icon_view_count=hot_view_count, user_id=request.user.member_id)

        return redirect('mychurch:myboards', church_no=church_no)

class MychurchAdmin(LoginRequiredMixin, TemplateView):

    def get(self,request, church_no):

        if    int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

        return  render(request, 'mychurch/admin/admin.html',{'church_no':church_no} )

class MyMembers(LoginRequiredMixin, TemplateView):
    #To-Do : code 정보에서 추출
    duty_cd = {'D001':'목사', 'D002':'장로', 'D003':'집사', 'D004':'일반신도'}

    #교인목록 조회
    def get(self,request, church_no):

        page = request.POST.get('page')
        searchStr = request.GET.get('searchStr')
        searchKey = request.GET.get('searchKey')

        if  int(church_no) < 1:    
            raise forms.ValidationError('Invalid access!!')

       # members = Believer.objects.filter(church_no_id=church_no).select_related('LightSaltUser__id').values( 'nick_name','duty_code', 'consult_yn', 'board_create_yn')
        if searchKey == "nick":
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id AND a.nick_name LIKE CONCAT('%%',%s,'%%')""", [church_no, searchStr])
        elif searchKey == 'id' :
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id AND b.member_id LIKE CONCAT('%%',%s,'%%')""", [church_no, searchStr])
        elif searchKey == 'duty' :
            #TO-DO : join with code table for searching..
            members =  Believer.objects.raw("""SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active \
        FROM LSMB003I as a , LSMB001M as b \
        WHERE a.church_no_id = %s AND a.member_id_id=b.id""", [church_no])
        else :
             members =  Believer.objects.raw('''SELECT a.id, b.member_id as uid, a.nick_name, a.duty_code, a.consult_yn,a.board_create_yn, b.is_admin, b.email, b.is_active FROM LSMB003I as a , LSMB001M as b WHERE a.church_no_id = %s AND a.member_id_id=b.id''', [church_no])
        
        paginator = Paginator(list(members), 20) # Show count board list per page
        try:
            page_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            page_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            page_list = paginator.page(paginator.num_pages)
        
        return  render(request, 'mychurch/admin/mychurch_members.html',{'church_no':church_no, 'members':members,  'duty_cd':self.duty_cd, 'page_list': page_list, 'page':page} )

    def post(self,request, church_no):
         #
        memberId = request.POST.get('member_id')
        memberNo = request.POST.get('member_no')
        type = request.POST.get('type')
        item = request.POST.get('item')
        value = request.POST.get('val')

        if type == 'M':
            LightSaltUser.objects.filter(member_id=memberId).update(**{item: value})
        else:

light_salt/templates/light_salt/mychurch/admin/admin_left.html
          <p class="menu-label"> 관리자</p>
	<ul class="menu-list">
                   <li>
		  <a href="#" class="is-active" aria-expanded="false"><span class="icon is-small"><i class="fa fa-tachometer"></i></span>
                           기본 정보</a> <!---->
	        </li>
	        <li>
		   <a href="{% url 'mychurch:mymembers' church_no=church_no %}" class="" aria-expanded="false"><span class="icon is-small"><i class="fa fa-rocket"></i></span>
                           교인 정보</a> <!---->
                   </li>
	       <li>
		    <a href="#" class="" aria-expanded="false"><span class="icon is-small"><i class="fa fa-rocket"></i></span>
                            Media </a> <!---->
                  </li>		   
                  <li>
	           <a href="{% url 'mychurch:myboards' church_no=church_no %}" class="" aria-expanded="false"><span class="icon is-small"><i class="fa fa-bar-chart-o"></i></span>
                          게시판 관리</a>
                            <!-- <span class="icon is-small is-angle"><i class="fa fa-angle-down"></i></span></a>
		             <ul data-v-43331adf="" class="collapse" style="height: 0px; display: none;">
			       <li><a href="#/charts/chartist" class=""> Chartist  </a></li>
			      <li><a href="#/charts/chartjs" class=""> Chartjs </a></li>
			      <li><a href="#/charts/peity" class=""> Peity </a></li>
			      <li><a href="#/charts/plotly" class=""> Plotly </a></li>
		             </ul>-->
	       </li>
	       <li>
	           <a><span class="icon is-small"><i class="fa fa-laptop"></i></span>
                           메뉴 관리</a>
                           <!--    <span class="icon is-small is-angle"><i class="fa fa-angle-down"></i></span></a> 
			    <ul data-v-43331adf="" style="height: 0px; display: none;" class="collapse">
				<li><a href="#/buttons" class=""> Buttons </a></li>
				<li><a href="#/form" class=""> Form </a></li>
				<li><a href="#/typography" class="">Typography </a></li>
				<li><a href="#/icons" class=""> Icons </a></li>
			     </ul>-->
	        </li>
	        <li>
		    <a href="#" class="" aria-expanded="false"><span class="icon is-small"><i class="fa fa-rocket"></i></span>
                              Layout 관리 </a> <!---->
                   </li>
	   </ul>

light_salt/templates/light_salt/mychurch/admin/mychurch_board_modify.html
{% extends 'mychurch/admin/admin.html' %}

{% block content %}
{% load mychurch_filter %}
<div class="tile is-ancestor">
<div class="tile is-8 is-parent">
<article class="tile is-child box">
    <h1 class="title">게시판 생성</h1>
    <div class="block">
        <form action="" method="post" name="frm" enctype="multipart/form-data">
	<input type="hidden" name="page" value="{{ page }}">
	 {% csrf_token %}
        <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">게시판 이름</label>
	</div>
	<div class="control is-grouped">
	    <p class="control is-expanded">
	        <input type="text" value="{{ board.board_title_name }}" name="board_title_name" placeholder="Name" class="input">
	    </p> 
	</div>
        </div>
       <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">게시판 관리자</label>
	</div>
	<div class="control is-grouped">
	    <p class="control is-expanded">
	        <input type="text" name="member_id" value="{{ board.member_id }}" readonly class="input">
	    </p> 
	</div>
        </div>
		
        <div class="control is-horizontal">
            <div class="control-label">
                <label class="label">게시판 유형</label>
            </div>
            <div class="control">
                <div class="select is-fullwidth">
	         <select name="board_type_code">
		  {% ifequal  board.board_type_code "BNRM" %}
	             <option value="BNRM" selected>일반형</option>
		   <option value="IMG">갤러리형</option>
	             {% else  %}
		  <option value="BNRM">일반형</option>
		  <option value="IMG" selected>갤러리형</option>
		  {% endifequal %}
	         </select>
                </div>
            </div>
        </div> 
		
        <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">페이지출력수</label>
	</div>
	<div class="control is-grouped">
	    <p class="control is-expanded">
	        <input type="text" name="page_count" placeholder="페이징수" class="input" value="{{ board.page_count }}">
	    </p> 
		
	    <div class="control-label">
	        <label class="label">리스트출력수</label>
	    </div>
	    <p class="control is-expanded">
	        <input type="text" name="list_count" placeholder="목록수" class="input" value="{{ board.list_count }}">
	    </p> 
	</div>
        </div>
	
        <div class="control is-horizontal">
            <div class="control-label">
                <label class="label">게시판 권한</label>
            </div>
            <div class="control">
                <div class="select is-fullwidth">
	         <select name="board_access_code">
		  {% ifequal  board.board_type_code "READ" %}
	              <option value="READ" selected>읽기</option>
		   <option value="RDWR">읽기/쓰기</option>
	             {% else  %}
		   <option value="READ">읽기</option>
		   <option value="RDWR" selected>읽기/쓰기</option>
		  {% endifequal %}
	         
	         </select>
                </div>
            </div>
        </div> 
	
        <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">파일첨부</label>
	</div>
	<div class="control is-grouped">
	    <label class="radio">
		<input type="radio" name="file_attach_yn" value="Y" {{board.file_attach_yn|checked:'Y'}} >Yes
	     </label>
	     <label class="radio">
		<input type="radio" name="file_attach_yn" value="N" {{board.file_attach_yn|checked:'N'}}> No
	     </label>

		
	    <div class="control-label">
	        <label class="label">댓글사용</label>
	    </div>

	    <label class="radio">
		<input type="radio" name="comment_use_yn" value="Y" {{board.comment_use_yn|checked:'Y'}}>Yes
	     </label>
	     <label class="radio">
		<input type="radio" name="comment_use_yn" value="N" {{board.comment_use_yn|checked:'N'}}> No
	     </label>
	
	</div>
        </div>
	
        <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">비밀글사용</label>
	</div>
	<div class="control is-grouped">
	     
	    <label class="radio">
		<input type="radio" name="passwd_use_yn" value="Y" {{board.passwd_use_yn|checked:'Y'}}>Yes
	     </label>
	     <label class="radio">
		<input type="radio" name="passwd_use_yn" value="N" {{board.passwd_use_yn|checked:'N'}}> No
	     </label>

	    <div class="control-label">
	        <label class="label">웹에디터사용</label>
	    </div>

	    <label class="radio">
		<input type="radio" name="webedit_use_yn" value="Y" {{board.webedit_use_yn|checked:'Y'}}>Yes
	     </label>
	     <label class="radio">
		<input type="radio" name="webedit_use_yn" value="N" {{board.webedit_use_yn|checked:'N'}}> No
	     </label>
	
	</div>
        </div>
	
        <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">이미지크기</label>
	</div>
	<div class="control is-grouped">
	    <p class="control is-expanded">
	        <input type="text" name="image_height" value="{{ board.image_height }}" class="input">픽셀 
	        <input type="text" name="image_width" value="{{ board.image_width }}" class="input">픽셀	
	    </p> 
		
	    <div class="control-label">
	        <label class="label">줄바꿈 게시물수</label>
	    </div>
	    <p class="control is-expanded">
	        <input type="text" name="image_br_count" value="{{ board.image_br_count }}" class="input">
	    </p> 
	</div>
        </div>
		
		
      <div class="control is-horizontal">
	<div class="control-label">
	    <label class="label">New기간설정(일)</label>
	</div>
	<div class="control is-grouped">
	    <p class="control is-expanded">
	        <input type="text" name="new_icon_terms" value="{{ board.new_icon_terms }}" class="input"> 
	    </p> 
	   
	    <div class="control-label">
	        <label class="label">Hot조회수 설정</label>
	    </div>
	    <p class="control is-expanded">
	        <input type="text" name="hot_icon_view_count" value="{{ board.hot_icon_view_count }}" class="input">
	    </p> 
	</div>
        </div>
	</form>
        <br><br>	
        <div class="control is-horizontal">
            <div class="control">
	      <a href="javascript:_submit();" class="button is-success is-outlined">
	          <span class="icon"><i class="fa fa-check"></i></span>
	          <span>Submit</span>
	     </a>&nbsp;&nbsp;
	     <a href="{% url 'mychurch:myboards' church_no=church_no %}" class="button is-danger is-outlined">
	         <span class="icon"><i class="fa fa-times"></i></span>
	         <span>Cancel</span>
	     </a>
            </div>
        </div>
	
    </div>	
</article>
</div>

</div>

<script>
  
  function _submit()
  {
    f = document.frm
	if( f.board_title_name.value == "") {
	    alert("게시판 이름을 입력하세요");
		f.board_title_name.focus();
		return;
	}
    else if( f.page_count.value == "") {
	    alert("페이지출력수를 입력하세요");
		f.page_count.focus();
		return;
	}
	else if( f.list_count.value == "") {
	    alert("리스트출력수를 입력하세요");
		f.list_count.focus();
		return;
	}
	
	f.action="{% url 'mychurch:myboard' church_no=church_no board_no=board_no %}";
	f.submit();
  }

</script>

 {% endblock content %}  

  
  

light_salt/templates/light_salt/mychurch/admin/mychurch_boards.html
{% extends 'mychurch/admin/admin.html' %}

{% block content %}
<div class="tile is-ancestor">
      <div class="tile is-parent">
         <article class="tile is-child box">
             <h4 class="title">게시판  관리</h4>
             <div class="table-responsive">     
                <table class="table is-bordered is-striped is-narrow">
                <thead>
                    <tr> 
                        <th align="center">번호</th> 
                        <th align="center">게시판명</th>
                        <th align="center">유형</th>
                        <th align="center">권한</th>
                        <th align="center">댓글사용</th>						
                        <th align="center">비밀글사용</th>
		  <th align="center">파일첨부</th>
                        <th align="center">수정</th>
                   </tr>
                </thead>
                <tbody>
               {% for board in boards %}
                 <tr>
                        <td> {{ board.board_no }}</td> 
                        <td>{{ board.board_title_name }}</td> 
		    <td>
		    {% ifequal  board.board_type_code "BNRM" %}
		         일반형
                         {% else  %}
                               갤러리형
                         {% endifequal %}							   
	             </td> 
		   <td>
		    {% ifequal  board.board_access_code "RDWR" %}
		         읽기/쓰기
                         {% else  %}
                              읽기
                         {% endifequal %}							   
	             </td> 
                        <td>{{ board.comment_use_yn}}  </td> 
                        <td>{{ board.passwd_use_yn}}  </td> 
                        <td>{{ board.file_attach_yn}}  </td> 
		   <td><a href="{% url 'mychurch:myboard' church_no=church_no board_no=board.board_no %}?page={{page}}" class="button is-small is-info is-active">수정</a> </td> 
                  </tr> 
               {% endfor %} 
               </tbody>
               </table>
             </div>
			
         </article>
		
    </div>
</div>
    <p class="control"><a href="{% url 'mychurch:myboards' church_no=church_no %}?mode=write" class="button is-danger">  게시판 추가 </a></p>
    <ul class="pagination">
	{% if page_list.has_previous %}
	  <li><a href="?page={{ page_list.previous_page_number }}">&laquo;</a></li>
	{% else %}
	  <li class="disabled"><span>&laquo;</span></li>
	{% endif %}
	{% for i in page_list.paginator.page_range %}
	  {% if page_list.number == i %}
		<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
	  {% else %}
		<li><a href="?page={{ i }}">{{ i }}</a></li>
	  {% endif %}
	{% endfor %}
	{% if page_list.has_next %}
	  <li><a href="?page={{ page_list.next_page_number }}">&raquo;</a></li>
	{% else %}
	  <li class="disabled"><span>&raquo;</span></li>
	{% endif %}
    </ul>	

<script>

    function changeInfo(id, item, type, val, no)
	{
	    $.ajax({
        type: "POST",
        url : '{% url 'mychurch:mymembers' church_no=church_no %}',
        data : {'csrfmiddlewaretoken': '{{ csrf_token }}', 
		        member_id: id , 
				item: item, 
				type: type,
				val: val,
				member_no: no
				},
        success:function(data){
          //$('body').append(data)

        },
		error: function(request, status, error){ 
		  alert(error);
		}
      });
	}

	
</script> 

 {% endblock content %}  

  
  